version: "3.1"

services:
  app:
    build:
      context: .

    ports:
      - "8080:8080"

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

